[MT-55]:(feature) Password support for share links
internxt/drive-mobile pull request #149
Opened 2022-10-25 18:34 UTC by PixoDev

Provide password enable/disable support for Drive share links for folders and files

2022-10-26 06:44 UTC, sg-gs commented on src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
> +              throw new Error('Function not implemented.');
why is this here?

2022-10-26 08:57 UTC, PixoDev commented on src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
> +              throw new Error('Function not implemented.');
Fixed

2022-11-04 09:39 UTC, sg-gs requested changes

2022-11-04 09:39 UTC, sg-gs commented on src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
> +    } else {
else is not required here, you are already doing a `return` on the if

2022-11-04 09:39 UTC, sg-gs commented on src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
> +      Clipboard.setString(generatedShareLink);
use a `return` here to remove the nesting which adds cognitive complexity.

2022-11-04 09:39 UTC, sg-gs commented on src/components/modals/SharedLinkSettingsModal/SharedLinkSettingsModal.tsx
> +    } else {
`else` is not required here

2022-11-04 14:09 UTC, sg-gs approved these changes

2022-11-04 18:57 UTC, merged