[MT-75]: New Drive navigation
internxt/drive-mobile pull request #160
Opened 2022-11-25 16:24 UTC by PixoDev

Improved Drive navigation using RN screens

2022-11-28 11:52 UTC, sg-gs requested changes

2022-12-01 11:01 UTC, sg-gs requested changes

2022-12-01 11:31 UTC, PixoDev commented on src/useCases/drive/trash.ts
> +    drive.trash
Just so the promise resolves, without waiting for `drive.trash.moveToTrash` to resolve, once it resolves we show the notification and we allow the undo

2022-12-01 15:08 UTC, sg-gs approved these changes

2022-12-01 15:08 UTC, sg-gs commented
You have conflicts with master

2022-12-01 15:13 UTC, merged